[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[edge_functions]]
  function = "protect"
  path = "/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
